# (Autor: Alex Roman)
# Descripcion: Analisis continuo de alta sensibilidad con Semgrep.

name: Semgrep High Sensitivity

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "17 2 * * *"

permissions:
  contents: read

jobs:
  semgrep-high-sensitivity:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container:
      image: semgrep/semgrep@sha256:98c2572fced2474539fd27cab3207ebd8e95e4e7aab4c3b381fdc5e2641d9941

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0

      - name: Scan
        run: |
          semgrep scan \
            --config auto \
            --config p/security-audit \
            --config p/secrets \
            --error \
            --strict \
            --disable-nosem \
            --historical-secrets \
            --no-git-ignore \
            --timeout 60 \
            --timeout-threshold 0 \
            --max-target-bytes 0 \
            --verbose \
            .
